### ISSUE TITLE
Receiver does not stop after count received packets

### ISSUE THREAD

**Issue by chenxy1988** [troglobit/mcjoin#1]
Hi Nilsson,

Many thanks for your sharing, that's a great util for mcast testing!

After doing fork the branch, I found -c parameter doesn't work on my local setup, I changed the code and move a size_t total = count * group_num to the top of loop() function as below commit.

https://github.com/chenxy1988/mcjoin/commit/f72959662235ae99327b55cea9b63df32d67ce8b

Thanks!
Xiangyu

**Comment by troglobit** [comment]
Hi!  Thank you for pointing this out, it was obviously not working.  I've pushed a slightly different fix, maybe you can test that as time permits.

I have a few other things I'll want to fix while I'm at it, like fixing default interface detection, but then there will be a new release.
