### ISSUE TITLE
Thank you for a great tool and suggestion for improvement.

### ISSUE THREAD

**Issue by ujhede** [troglobit/mcjoin#11]
I have been looking for and testing tools for testing multicast for years and this is simply the very best I have come across. Keep up the good work,

Especially I really like the newer animated view.

I would like to suggest making it possible to view packet and byte throughput numbers (not just counter) for each joined group.  Looks like some throughput information is already calculated to control the speed of the "spinner".

Maybe add an option to control sampling interval and scale of the byte throughput numbers.

**Comment by troglobit** [comment]
Thank you for the kind words, happy other people find it useful too! :smiley: 

More stats and alternate views are planned. I'll see what I can do in upcoming releases.

**Comment by troglobit** [comment]
Just pushed a set of new presentation modes/views.  One of which includes a rate/bytes view. Use 't' to toggle between views. 

The next release, v2.9, will be available within a few days :)
