### ISSUE TITLE
Seperate listen port per group ?

### ISSUE THREAD

**Issue by ujhede** [troglobit/mcjoin#18]
Would it be possible to add a way to have mcjoin use a differnet listen port per group when joining multiple groups ?  Maybe use the stnadard syntax group:port or group+num:port

Thanks for a great tool.

**Comment by troglobit** [comment]
Yes, anything is possible.  Your patch is welcome ;-)

**Comment by ujhede** [comment]
I wish I was able to provide a patch, but my coding skills are probably not at a level where any PR will get accepted :-) 

On another subject does the Rate and Kb counters in the new view work?  For me they both just stay at 0 even if packet count increments.

**Comment by troglobit** [comment]
Thanks to the amazing work by @adamyg, the next release of mcjoin will have support for this! :smiley:

**Comment by troglobit** [comment]
I've just updated the usage text to the program to include the new `:PORT` syntax for groups.  The README man manual page will be updated tomorrow.
