### ISSUE TITLE
IGMP/MLD monitoring

### ISSUE THREAD

**Issue by lars18th** [troglobit/mcjoin#21]
Hi,

I need to know if I could do a monitoring of IGMP/MLD messages (joins/leaves to groups) using the `mcjoin` tool. Or if I can do this with another tool. My objective is to start/stop some scripts based on the group state.

Thank you.

**Comment by troglobit** [comment]
Nope, that's not what mcjoin does. In fact, it does not do any IGMP/MLD join/leave at all but via socket options ask the kernel to receive/not-receive multicast groups.  You could try scripting tcpdump/tshark instead.

**Comment by troglobit** [comment]
I'm sure there are lots of people out there more competent than I wrt these programs and how to script them.  Respectfully, it is also not my responsibility as maintainer of this project to help you with that.

**Comment by lars18th** [comment]
OK, @troglobit .

Don't worry. I'm only searching for help about this.
Thank you.
