### ISSUE TITLE
100% cpu usage in daemon mode

### ISSUE THREAD

**Issue by pieterverberne** [troglobit/mcjoin#26]
`mcjoin -s -d` results in 100 cpu usage. A quick ptrace shows mainly:

pselect6(5, [0 4], NULL, NULL, NULL, NULL) = 1 (in [0])
read(0, "", 1)                          = 0

**Comment by troglobit** [comment]
Well that's not right!  Good catch, I'll have a look at it later this week, unless someone else beats me to it.

**Comment by troglobit** [comment]
Sometimes bugs are shallow. Those are the days we only dream of, like today :)

**Comment by pieterverberne** [comment]
Great work. Thanks.
