### ISSUE TITLE
Source/group parser cuts of group addresses when using IPv6 SSM

### ISSUE THREAD

**Issue by pascalparietti** [troglobit/mcjoin#28]
Groups are cut off when the argument exceeds 49 characters:

`mcjoin fd6f:7b5e:3918:9728:d8fa:2afd:d864:e944,ff3e::f2ce:7765` results in joining group `ff3e::f2c` instead of `ff3e::f2ce:7765`

The issue is caused at the following line:
https://github.com/troglobit/mcjoin/blob/3d33bc2233b63d42008ce810f53c232776b3e3bd/src/mcjoin.c#L825

buf size has to be at least: 2 addresses, 3 delimiters, 2 brackets, 5 port digits and 1 zero terminator to support `mcjoin source,[group0]:port+num`

suggested change:
`char buf[2 * INET_ADDRSTR_LEN + 11];`

**Comment by troglobit** [comment]
There fixed, hope it works better now!
