### ISSUE TITLE
Publish docker image

### ISSUE THREAD

**Issue by gclawes** [troglobit/mcjoin#3]
It's useful in container environments to have mcjoin for testing.  I've created a PR #2 to build mcjoin in docker and package it in an image based on `debian:stretch`.  This could be published to https://hub.docker.com/u/troglobit with DockerHub automated builds.

**Comment by gclawes** [comment]
The following command should work to build the latest tag manually once this has been merged:

```
$ git checkout v2.4
$ git checkout master -- Dockerfile
$ docker build -t troglobit/mcjoin:2.4 .
$ docker push troglobit/mcjoin:2.4
```

**Comment by troglobit** [comment]
Thanks!

Same question as with the pimd docker image, curious why Debian instead of Alpine?  In particular for mcjoin which is a tiny application to carry the massive overhead of Debian.

**Comment by gclawes** [comment]
No particular reason, I can submit a PR to switch it in both projects.

**Comment by troglobit** [comment]
That would be really great, thanks! Maybe uninstall autotools as well after autogen.sh ...

You can close these issues by putting "Fix #NUM: GIT message" in your commit. When I merge the PR GitHub will automatically close the issue.

**Comment by gclawes** [comment]
It's a multistage build, so it's a fresh image after the second `FROM`, only thing that gets carried over is the binary, no need to uninstall.

**Comment by gclawes** [comment]
Once this is built, can you publish it to dockerhub?

**Comment by troglobit** [comment]
Aha, cool good to know! :)

Sure thing, I'll merge, build, and push both of them to dockerhub after work tonight :+1:

**Comment by troglobit** [comment]
Done!  I had to modify the Dockerfile slightly, but as a side effect it's now stand-alone
