### ISSUE TITLE
mcjoin -s in docker container fails with: No interface (eth0), or no IPv6 address yet, rc 0: No error information

### ISSUE THREAD

**Issue by henk52** [troglobit/mcjoin#7]
Hi

When I run mcjoin -s in a container it reports: No interface (eth0), or no IPv6 address yet, rc 0: No error information

Do I need to give special rights to the container?

Reproduction:

1. git pull
2. docker build .
3. docker run -it xxx sh
4. run it in the container
```
mcjoin -s -l debug
Found default intefaces eth0
NOFILE: current 1048576 max 1048576
NOFILE: set new current 2058 max 1048576
Found eth0 addr 172.17.0.2
Valid iface eth0, ifindex 118, addr 172.17.0.2
Sending on iface eth0 addr 172.17.0.2 ifindex 118
No interface (eth0), or no IPv6 address yet, rc 0: No error information
No interface (eth0), or no IPv6 address yet, rc 0: Interrupted system call
No interface (eth0), or no IPv6 address yet, rc 0: Interrupted system call
No interface (eth0), or no IPv6 address yet, rc 0: Interrupted system call
...
```

I've tried it on an Ubuntu 18.04 host and a Fedora 30 host.

  Thanks

**Comment by troglobit** [comment]
Well, docker applications are *contained* by default.  To use the hosts network interfaces you have to tell docker to open that up.  Like so:

     docker run --rm --network host troglobit/mcjoin:latest mcjoin -s 225.1.2.3
