### ISSUE TITLE
Doesn't send IPv4 packets if IPv6 is not available 

### ISSUE THREAD

**Issue by alexeys85** [troglobit/mcjoin#8]
I have Ubuntu 20.04 with disabled Ipv6 and no Ipv6 address on interfaces. In that cast sender just can't send ipv4 packets with error like: No interface enp2s0, or no IPv6 address yet...
My simple workaround was just comment these:
https://github.com/troglobit/mcjoin/blob/0e287eec9b96f6920aa12d15171be3a34206d03b/src/mcjoin.c#L254-L255
and these
https://github.com/troglobit/mcjoin/blob/0e287eec9b96f6920aa12d15171be3a34206d03b/src/mcjoin.c#L260-L261
lines, and make appropriate check after this line:
https://github.com/troglobit/mcjoin/blob/0e287eec9b96f6920aa12d15171be3a34206d03b/src/mcjoin.c#L268

**Comment by troglobit** [comment]
Ouch, my bad.  I'll have a look during the weekend to see what I can do. Thank you for bringing this to my attention! :)

**Comment by troglobit** [comment]
There, should work better now.  Only a few things more to look into for v2.7 before I release that.
